upmc_convirt:
  name: "upmc"
  data_type: "imagetext_contrastive"
  data_dir: "/ocean/projects/asc170022p/shg121/PhD/RSNA_Breast_Imaging/Dataset"
  img_dir: "External/UPMC/DICOM/images_png_CC_MLO"
  data_path: "External/UPMC/upmc_dicom_consolidated_final_folds_BIRADS_num_1_report.csv"
  text_max_length: ${base.text_max_length}
  convirt_mode: True
  data_frac: 1.0
