rsna_wo_period:
  name: "rsna"
  data_type: "imagetext"
  data_dir: "/ocean/projects/asc170022p/shg121/PhD/RSNA_Breast_Imaging/Dataset"
  img_dir: "RSNA_Cancer_Detection/train_images_png"
  data_path: "RSNA_Cancer_Detection/rsna_breast_clip_without_period.csv"
  text_max_length: ${base.text_max_length}
  data_frac: 1.0
